### ISSUE TITLE
Add search by metadata link to home page

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1034]
We need to figure out the best method to add a link to https://data.sennetconsortium.org/discover/metadata on the home page. The navbar is getting cluttered so we may need to restructure that or add a second one. Another option might just to have a section only on the home page that links out to the various search pages: `metadata` and `files`.

**Comment by maxsibilla** [comment]
- [ ] Change the link for `C57BL/6J-Kit<W-39J> Mouse Sources` to use the strain `C57BL/6`
- [ ] Investigate why `All Block Samples` returns an error: https://data.sennetconsortium.org/search/metadata?size=n_10000_n&filters%5B0%5D%5Bfield%5D=entity_type&filters%5B0%5D%5Bvalues%5D%5B0%5D=Sample&filters%5B0%5D%5Btype%5D=any&sort%5B0%5D%5Bfield%5D=last_modified_timestamp&sort%5B0%5D%5Bdirection%5D=desc
- [ ] Change the link for `All Protein Datasets` to `All RNA Datasets` and use `RNA` as the filter

**Comment by tjmadonna** [comment]
@maxsibilla The All Blocks Sample returns a 503 response from the `search-api`. The error message is:

Trying to create too many buckets. Must be less than or equal to: [65535] but was [81065]. This limit can be set by changing the [search.max_buckets] cluster level setting.

**Comment by maxsibilla** [comment]
@tjmadonna we might need to rethink how we request this data then. We could simply increase the `max_buckets` but that might just kick this issue down the road. We should first try to identify why so many buckets are being created and then go from there to determine how to modify the request.

**Comment by tjmadonna** [comment]
@maxsibilla After looking into this a little more, I see that an All Block Samples request could potentially contain three number range facets (with histograms). I think this might be the issue. I'll try to confirm and fix that tomorrow.

**Comment by maxsibilla** [comment]
@tjmadonna in that case we might just need to show that on request (as opposed to by default)

**Comment by tjmadonna** [comment]
This is being caused by `metadata.volume_value` histogram aggregation. The production data has a maximum value of 80850 and we are setting an interval size of 1.

min = 9000
max = 80850.0

**Comment by maxsibilla** [comment]
Yea that would do it. I guess the initial question is do we need to show this and if so should we display it as a histogram

**Comment by tjmadonna** [comment]
We're probably going to run into the same issue with `metadata.weight_value` and `metadata.pathology_distance`. Right now I don't believe we have any metadata with those values set.
