### ISSUE TITLE
Add support for typing a list of UUIDs or SenNet IDs for the ancestors

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1065]
<img width="1266" alt="image" src="https://github.com/sennetconsortium/portal-ui/assets/7218802/5bf5af60-75c0-480f-9cb7-0a845aa1572d">
<img width="1288" alt="image" src="https://github.com/sennetconsortium/portal-ui/assets/7218802/6cda2b6f-c106-4598-9350-2b818886d07a">

**Comment by libpitt** [comment]
https://ingest.hubmapconsortium.org/new/collection
