### ISSUE TITLE
Replace all references of `data_types` with  `dataset_type`

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1090]
New dataset_type values - https://ontology-api.dev.hubmapconsortium.org/valueset?parent_sab=HUBMAP&parent_code=C003041&child_sabs=HUBMAP

This needs to be done in:

- [x] Faceted search
- [x] Dataset view page badges (including metadata)
- [x] Dataset registration/edit page the drop down needs to reference the new UBKG link and the title should read `Dataset Type`

**Comment by libpitt** [comment]
Extra notes for future reference:

> Primary datasets will have the creation_action of “Create Dataset Activity” and the `dataset_type` of something supported by soft assay (e.g. Visium).
> Component datasets will have the creation_action of “Multi-Assay Split” and `dataset_type of` a soft assay (e.g. RNAseq).
> Derived/processed datasets will have the creation_action of “Central Process” and a `dataset_type` of a soft assay with a bracket (e.g. Auto-fluorescence [Image Pyramid])
