### ISSUE TITLE
Change Title of Register Upload Page

### ISSUE THREAD

**Issue by bhonick** [sennetconsortium/portal-ui#1091]
Hi @maxsibilla , could the title of the Register Upload page be changed to "Register Upload"? Currently it has the title of "Upload Information": https://data.sennetconsortium.org/edit/upload?uuid=register. 

Ideally, I'd like it to match up stylistically to the Bulk Datasets page: https://data.sennetconsortium.org/edit/bulk/dataset?action=register. Thanks!

**Comment by maxsibilla** [comment]
@bhonick We can do something regarding the title but not the style of the page. We have 2 clear distinctions for registration/editing entities: the form for individual and the wizard for bulk. It doesn't make sense to create a wizard for the registration of uploads

**Comment by bhonick** [comment]
The title is the main thing I would ideally like to be tweaked, thanks!
