### ISSUE TITLE
Fix navigation bar inconsistency

### ISSUE THREAD

**Issue by tjmadonna** [sennetconsortium/portal-ui#1092]
Navigation bar font sizes are inconsistent between search page and entity detail page.

Search Page
![Screenshot 2023-12-08 at 1 06 41 PM](https://github.com/sennetconsortium/portal-ui/assets/8182608/00dd0b71-1006-403b-993b-749269bf13dc)

Entity Detail Page
![Screenshot 2023-12-08 at 1 07 19 PM](https://github.com/sennetconsortium/portal-ui/assets/8182608/710f6391-e12f-4556-abac-c8151f53c460)

**Comment by maxsibilla** [comment]
@tjmadonna @libpitt This is being caused by CSS coming from `Provenance UI` specifically on the div with the ID `__next`
