### ISSUE TITLE
`getUBKGFullName` needs to be modified to just return the `term` from UBKG for dataset_type

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1116]
The soft assay (dataset_type) endpoint in UBKG has been updated (https://ontology-api.dev.hubmapconsortium.org/valueset?parent_sab=SENNET&parent_code=C003041&child_sabs=SENNET) but the names are not showing up correctly in the drop down:
<img width="1489" alt="image" src="https://github.com/sennetconsortium/portal-ui/assets/7218802/3af62d77-a327-448c-bd76-503a5592f866">

I think `getUBKGFullName` in functions.js is still referencing the /datasets endpoint.

**Comment by libpitt** [comment]
![Screen Shot 2023-12-18 at 12 45 33 PM](https://github.com/sennetconsortium/portal-ui/assets/115558393/e3f944ee-e7ef-40ff-8401-665c9db35115)

Updated.
