### ISSUE TITLE
Reverting a dataset is not triggering Search API reindex

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1125]
In production is seems that when a dataset is reverted from invalid to new the Search API is not being triggered to reindex the dataset

**Comment by tjmadonna** [comment]
I cannot replicate this issue on dev. I added more informative error logs to Entity API schema triggers to help diagnose any issues. That PR is [here](https://github.com/sennetconsortium/entity-api/pull/255).
