### ISSUE TITLE
Ensure front-end support for multiple organ constraint error message

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1147]
Related to https://github.com/sennetconsortium/entity-api/issues/257

We need to check that the error message produced by the Entity API clearly displays to the user in the portal

**Comment by libpitt** [comment]
Formatting specifically handled in this commit: https://github.com/sennetconsortium/entity-api/commit/9f111912c7e0ded3037888e34cd6504674f60515
