### ISSUE TITLE
Add `Human Reference Atlas` section to organ specific view pages

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1150]
See https://portal.hubmapconsortium.org/organ/kidney#Human%20Reference%20Atlas

This section loads an iFrame: https://portal.hubmapconsortium.org/iframe/organ?iri=http://purl.obolibrary.org/obo/UBERON_0002113

Utilizes the `hra-api` endpoint (SenNet's is https://apps.humanatlas.io/sennet-hra-api/v1): 
https://github.com/hubmapconsortium/portal-ui/blob/309ae9688283fb25b8f9442abe5bb515913bb7e9/context/app/static/js/pages/Iframe/Iframe.jsx#L20

**Comment by tjmadonna** [comment]
It looks like there are some hardcoded urls in the library.
https://github.com/hubmapconsortium/ccf-ui/blob/332cbcf7cca411cfdf1b7a2bce141d112a517c67/projects/ccf-organ-info/src/app/modules/link-cards/link-cards.component.ts#L20

**Comment by maxsibilla** [comment]
@tjmadonna We can probably ignore the section `Register Tissue`. For `Explore Tissue` we can point to https://data.sennetconsortium.org/ccf-eui

**Comment by maxsibilla** [comment]
Or you can use this https://sennetconsortium.github.io/ccf-preview/ccf-rui.html

**Comment by tjmadonna** [comment]
I get a `Unknown IRI: http://purl.obolibrary.org/obo/UBERON...` for numerous Organs. I have to look into this a little more.
- Adipose Tissue
- Blood
- Bone
- Bone Marrow
- Breast
- Lung (Left)
- Lung (Right)
- Muscle
- Ovary (Left)
- Ovary (Right)

**Comment by maxsibilla** [comment]
Hmm the Uberon codes provided by UBKG should resolve
`Adipose Tissue`  maps to UBERON:0001013:
https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001013

**Comment by bherr2** [comment]
The only IRIs supported by the ccf-organ-info component are those that have a 3D Reference Organ. Adipose does not have an associated reference organ and thus does not show any 3d organ / info.

**Comment by bherr2** [comment]
You should probably check if the organ/IRI is supported by the HRA / RUI and then conditionally include the web component or not.

**Comment by tjmadonna** [comment]
@bherr2 Is there anyway to override the button URLs? For instance, the "Register Tissue" button currently takes you to `https://hubmapconsortium.github.io/ccf-ui/rui/`. 

![Screenshot 2024-01-11 at 2 05 11 PM](https://github.com/sennetconsortium/portal-ui/assets/8182608/7499751c-2123-4c24-b345-600dc269e8e8)

**Comment by bherr2** [comment]
No, but it should be possible to add those as web component inputs. What would you set the URLs to?

**Comment by tjmadonna** [comment]
I wanted to set the SenNet equivalent URLs.

**Comment by bherr2** [comment]
Ok, please submit an issue to [ccf-ui](https://github.com/hubmapconsortium/ccf-ui/issues) and we'll get it scheduled.

**Comment by tjmadonna** [comment]
Submitted [issue #1220](https://github.com/hubmapconsortium/ccf-ui/issues/1220) in `ccf-ui`.

**Comment by maxsibilla** [comment]
https://apps.humanatlas.io/us6/
EUI > Organ Information

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>EUI Organ Info Web Component</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500&amp;display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined" rel="stylesheet" />
    <link href="https://cdn.humanatlas.io/ui/ccf-organ-info/styles.css" rel="stylesheet" />
    <script src="https://cdn.humanatlas.io/ui/ccf-organ-info/wc.js" defer></script>
  </head>
  <body style="margin: 0">
    <ccf-organ-info
      base-href="https://cdn.humanatlas.io/ui/ccf-organ-info/"
      use-remote-api="true"
      remote-api-endpoint="https://apps.humanatlas.io/api/v1"
      organ-iri="http://purl.obolibrary.org/obo/UBERON_0002107"
    >
    </ccf-organ-info>
  </body>
</html>
```

**Comment by bherr2** [comment]
For sennet-only data, switch the remote-api-endpoint to "https://apps.humanatlas.io/sennet-hra-api/v1"

**Comment by bherr2** [comment]
PS it's in production now! See https://apps.humanatlas.io/us6/

**Comment by maxsibilla** [comment]
Thanks @bherr2 I have tried to specify every configuration parameter but I can't seem to get any numerical results for tissue data providers, sources, etc...


![Image](https://github.com/user-attachments/assets/ff9be0c6-c511-4788-9a21-ab323067000e)

```
            <ccf-organ-info
                organ-iri={uberonUrl}
                hubmap-data-service='search-api'
                hubmap-portal-url='https://data.sennetconsortium.org/search'
                hubmap-data-url='https://search.api.sennetconsortium.org/entities/search'
                hubmap-asset-url={getAssetsEndpoint()}
                use-remote-api='true'
                donor-label='Sources'
                token={getCookie('groups_token')}
                remote-api-endpoint="https://apps.humanatlas.io/api"
                eui-url='https://data.sennetconsortium.org/ccf-eui'
                rui-url='https://apps.humanatlas.io/rui'
                asctb-url='https://hubmapconsortium.github.io/ccf-asct-reporter/'
                hra-portal-url='https://humanatlas.io/'
                online-course-url='https://expand.iu.edu/browse/sice/cns/courses/hubmap-visible-human-mooc'
                paper-url='https://www.nature.com/articles/s41556-021-00788-6'
            />
```

**Comment by maxsibilla** [comment]
@bherr2 It looks like the `token` parameter is not overwriting the default value of `9070a30087cc3562131d1069c8497f6b`. Its making the following request: https://apps.humanatlas.io/api/v1/aggregate-results?ontology-terms=http://purl.obolibrary.org/obo/UBERON_0000955&sex=male&token=9070a30087cc3562131d1069c8497f6b

This link does work when I pass it a token generated by Globus on the SenNet side

**Comment by bherr2** [comment]
Ok, I'll look into it on Monday! We've made some changes to the API so we may need to update the example.

**Comment by bherr2** [comment]
Also, EUI is specified similarly here:

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>SenNet - HRA Exploration User Interface</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500&amp;display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined" rel="stylesheet" />
    <link href="https://cdn.humanatlas.io/ui/ccf-eui/styles.css" rel="stylesheet" />
    <script src="https://cdn.humanatlas.io/ui/ccf-eui/wc.js" defer></script>
  </head>
  <body>
    <ccf-eui
      base-href="https://cdn.humanatlas.io/ui/ccf-eui/"
      logo-tooltip="SenNet Data Portal"
      home-url="https://data.sennetconsortium.org/"
      data-sources='["https://apps.humanatlas.io/api/ds-graph/sennet?token={getCookie('groups_token')}"]'
      theme="sennet"
      login-disabled="true"
    ></ccf-eui>
  </body>
</html>
```

**Comment by maxsibilla** [comment]
@bherr2 awesome thank you for this!

**Comment by bherr2** [comment]
Also, I remembered why the female heart blocks weren't showing. Its because all the female heart registrations were somehow registered to the male heart! All the registrations look to have been done by "Lorena Rosas". Dan Qaurooni @danqaurooni may already be aware, but if assistance is needed for updating the registrations, he can help!

**Comment by maxsibilla** [comment]
@tjmadonna 

- [ ] Remove laterality from organ page 
- [ ] 2 new properties
    - [ ] Is hra supported
    - [ ] Organ URL - determine HRA link AND the link at top of page (uberon or fma)
- [ ] Only rely on config and not UBKG for what organs
