### ISSUE TITLE
Add support for new status and badge `Incomplete`

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1197]
Add support to `getStatusColor` and `getStatusDescription` in functions.js

Add to the badge.scss:
```
.badge-warning {
  background-color: #ffc107;
  color: #212529;
}
```

**Comment by maxsibilla** [comment]
@bhonick can you supply a description for this status? You can see existing examples here https://github.com/sennetconsortium/portal-ui/blob/ed8741c47081e55a5e381a79b36e7f9e428de6cf/src/components/custom/js/functions.js#L202

**Comment by bhonick** [comment]
@maxsibilla Sure! I actually think that the current message for `New` would work well for `Incomplete`: `The data provider has begun to upload data but is not ready for validation or processing via the ingest pipeline.` Perhaps `New` could have a new definition like `The Globus directory is ready for data upload.`.
