### ISSUE TITLE
Create a new view page to support job queue

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1245]
To support the changes in the Ingest API to the bulk validation/ingestion of entities and metadata we will need to create a page where users can monitor these processes. The primary component will be a table that will display:
`run_id`, a description of the run (e.g. validating metadata of <filename>.tsv or registering sources from <filename.tsv), the status of the run, an action column.

Action column explained:
This column might have a couple of different buttons to trigger various actions depending on the type of run and the results. 
Examples:

- If the run is hitting`/sources/bulk/validate` and it completes without any issues we should then allow the user to initiate a new run which is to register those sources.
- If the run is hitting `/sources/bulk/validate` but it fails then we want to display to the user which rows it failed on and then allow the user to resubmit a new run with an updated TSV.
- If the status is complete (regardless of success/failure) we might want to have an option to delete that run (which prompt).
- If the status is processing we might want to allow for the user to cancel that run (if possible) (also with prompt).

This queue information may be utilizing memcache in which case we will need to create a new endpoint in the Ingest API to access this.

**Comment by libpitt** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events
 https://medium.com/@rajreetesh7/push-notification-in-react-and-next-js-app-using-node-js-da39ad1332ef

**Comment by libpitt** [comment]
> When a user validates metadata, then proceeds to register it, from a UI perspective, as long as these two jobs are available from GET /jobs (ie. one of them hasn’t been deleted), I am able to do things like grouping etc. If say we delete the register related job, no longer able to match up from the UI without some dedicated field in the response of the original validate job.

Solutions:
1. From the UI, do not allow user to delete just register job, but will subsequently also delete corresponding validate job
2. From api, update validate job after successful register job with property showing job was fulfilled
3. From api, delete validate job after successful register job
4. Do nothing, re-registering a validation does not corrupt the respective entity anyways (except for changes in updated timestamp)
