### ISSUE TITLE
Add ability to search RUI location information

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1256]
From the data provider:
```
How can I search the tissue blocks by their anatomical location, e.g., in pancreas I want all blocks that are "tail of pancreas". The information exists in two places: in "Lab Notes" of the block (visible only in editing mode) and in the RUI registration.

Can the "Lab Notes" of the block be appended to the block metadata?

 

I managed to filter for "tail of pancreas" in CCF-EUI (screenshot below), however I cannot find this locations in "Search Entities" on the Data Sharing Portal.

It would be necessary to search datasets by the block locations, e.g., to select all datasets from "tail of pancreas" location.
```

**Comment by maxsibilla** [comment]
Will need to reach out to @bherr2  to identify how to query this specific information

**Comment by bherr2** [comment]
One quick thing, you will likely want to index the "ccf_annotations" array that is in the RUI data. Check out <https://github.com/hubmapconsortium/ccf-ui/blob/main/rui-registration-data-format.md> for more info. But essentially this is an array of uberon terms/anatomical structures that the tissue block collided with within the RUI. You can probably then look them up with the the UBKG's ontology API for further enrichment.

**Comment by maxsibilla** [comment]
@bherr2 We noticed that the PURLs point to at least 2 different sites: http://fma.si.washington.edu/browser and https://www.ebi.ac.uk/ols4/ontologies/uberon/classes. Are there any other use cases we should be aware of?

**Comment by bherr2** [comment]
It should just be those two. FMA and UBERON.

**Comment by maxsibilla** [comment]
Are you aware of any API for FMA? We can't see to programmatically grab the `preferred name`

**Comment by bherr2** [comment]
Sure, we have FMA loaded into the HRA-KG and can be queried from there. Not sure if it's in UBKG yet. You can download the OWL file from here: https://lod.humanatlas.io/vocab/fma/v5.0.0/ or you can do a lookup with our SPARQL server at <https://lod.humanatlas.io/sparql>. 

The sparql query would look something like this:
```sparql
SELECT ?label
FROM <https://purl.humanatlas.io/vocab/fma>
WHERE {
  <http://purl.org/sig/ont/fma/fma7265> <http://www.w3.org/2000/01/rdf-schema#label> ?label .
}
```
And here is a YASGUI link to play around with: https://api.triplydb.com/s/ECyClACc5

**Comment by tjmadonna** [comment]
@bherr2 I was able to get the label from the `POST https://lod.humanatlas.io/sparql` endpoint. Thank you.

Do you know if there is an API Key or any rate limiting on that endpoint? I haven't run into any issues yet. I was just wondering if this is something we should look out for.

**Comment by bherr2** [comment]
Nope, it should be pretty scalable. There is a 1 minute timeout, but I don't think you'll hit up against that for the queries you're doing. We use this endpoint in our production code as well and it's been up to the challenge thus far!
