### ISSUE TITLE
Add manifest file file generation support

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1288]
Add the ability to generate a manifest file that can be used with the SenNet Command Line Transfer Tool for bulk transfer of data.  This should be a new option in the dropdown menu BUT for only Datasets

![image](https://github.com/sennetconsortium/portal-ui/assets/7218802/b0f260c2-07d5-4202-8ca6-d7469888993e)

**Comment by libpitt** [comment]
Related old issues: https://github.com/sennetconsortium/portal-ui/issues/265
https://github.com/sennetconsortium/portal-ui/issues/775

**Comment by maxsibilla** [comment]
For the time being we only want to create a manifest file of the datasets selected. At a later date we may want to add an option to include derived dataset files as well. 

Based on the format of the file (https://docs.sennetconsortium.org/libraries/clt/#example) we can potentially just create a file that contains the SenNet ID and `/` as the directory specifier
