### ISSUE TITLE
Replace status `Started` with a progress bar that displays the actual percentage complete

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1353]
This will only be for registration jobs as it is not possible to generate a percent complete with the IVT. @tjmadonna will be updating the metadata of the job with a new property that will contain this percentage to be displayed.

**Comment by tjmadonna** [comment]
There will be a field on the returned job named `progress` that will be an integer between 0 and 100

**Comment by maxsibilla** [comment]
Related Ingest API branch/PR https://github.com/sennetconsortium/ingest-api/pull/405
