### ISSUE TITLE
Add Data Products to summary section

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1401]
See https://portal.hubmapconsortium.org/browse/dataset/dd648e4648238b25a7d1062669ea89af
<img width="1110" alt="image" src="https://github.com/sennetconsortium/portal-ui/assets/7218802/f0734ba0-7c4b-42eb-b841-8693c6f0d877">

This will display in a similar way as the `Files` section: if the primary dataset is being viewed then show the `Data Products` of the derived dataset and if the derived dataset if being viewed then just base it off of that dataset's files.

You can see which files are `Data Products` here: https://data.dev.sennetconsortium.org/dataset?uuid=dda88332e2ffb093d64db9eec094d749#Files

Specifically its in `files` where the property `is_data_product` exists and is "True"

**Comment by libpitt** [comment]
@maxsibilla What about if it is a component dataset? Those don't have files?

**Comment by maxsibilla** [comment]
> @maxsibilla What about if it is a component dataset? Those don't have files?

@libpitt This particular section will only exist on processed and primary datasets. Also it will only display if there are `files` for the processed dataset AND at least one file has the property `is_data_product` set to true
