### ISSUE TITLE
Utilize react lazy or suspense for ancestry calls

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1562]
Currently these calls are behind an `await` but this slows down the initial load time of the page. If we can lazy load components that require the response of these calls users will be able to see some basic page components right away.

**Comment by libpitt** [comment]
Look at Promise.all or Promise.allSettled

**Comment by libpitt** [comment]
> 1. If we are still waiting for get_read_write_privileges (isAuthorizing()) then show spinner
> 
> - If no privileges (!authorized => this needs to check public access)- unauthorized message
> - If privileges - this doesn’t immediately resolve to anything
> 
> 2. IF privileges (authorized)
> 
> - AND data is null (still waiting for this response) - spinner
> - AND data has any value (either true - creating, or has actual data) - show page
