### ISSUE TITLE
Modify results page to utilize Elasticsearch paginate - Datatable

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1572]
This card requires two major components to be modified: the datatable that displays the results and the actual query issued to Search API/Elasticsearch. Related card for the query: https://github.com/sennetconsortium/portal-ui/issues/1573

Instead of returning the whole of the Elasticsearch index based on the query, we will limit it to however many items the user specifies via the dropdown menu:

![Image](https://github.com/user-attachments/assets/d60a26d5-b6f7-41eb-a7da-a58730f1f635)

We will need to override the functionality of the following Datatable features:

- [ ] Sorting by column will need to issue a query to the Search API/Elaticsearch to specify which property is to be sorted and if its in ascending or descending order 

![Image](https://github.com/user-attachments/assets/a5a51718-3e47-48c5-af07-ee7849b30f8f)

- [ ] Clicking the arrows needs to be in sync with the paginate call made to Elasticsearch

![Image](https://github.com/user-attachments/assets/e12916d1-189b-4e9f-ae66-ba47e8c943b0)

**Comment by maxsibilla** [comment]
Potentially relevant Search UI component https://www.elastic.co/docs/current/search-ui/api/react/components/paging

**Comment by libpitt** [comment]
https://ant.design/components/table

Search for "Ajax" on the page.

**Comment by libpitt** [comment]
**Some huge custom functionality added with the current react-data-table-component:**
1. Bulk export and dropdown
- Bulk export should be fairly straightforward (though maybe tedious) to replace with antd's Table component but the custom dropdown in the header, will be a bit tricky to get going
2. Column reordering and that order is saved and reflected in bulk exported file
3. Dynamic column toggling

**Major limitation of react-data-table-component:**
The rows per page `Select` component user `defaultValue` prop, and but not `value` prop. So cannot trigger a dynamic change without "hacks".

Biggest hurdle besides reimplementing the above custom features, would be replacing the many places that this component exists.
