### ISSUE TITLE
Oraganize `Metadata` facets

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1576]
See https://data.sennetconsortium.org/search/metadata?size=n_10000_n&filters%5B0%5D%5Bfield%5D=entity_type&filters%5B0%5D%5Bvalues%5D%5B0%5D=Sample&filters%5B0%5D%5Btype%5D=any&filters%5B1%5D%5Bfield%5D=sample_category&filters%5B1%5D%5Bvalues%5D%5B0%5D=Block&filters%5B1%5D%5Btype%5D=any&sort%5B0%5D%5Bfield%5D=last_modified_timestamp&sort%5B0%5D%5Bdirection%5D=desc

The various facets for `storage` and `preparation` should be next to each other. Easiest solution is to sort all facets alphabetically but keep `Entity Type` and `Sample Category` at the top.

**Comment by libpitt** [comment]
Hmm. @maxsibilla  Is this just when Sample and Block are selected, or should it sort alphabetically regardless?

**Comment by maxsibilla** [comment]
@libpitt This is the case for Block, Section, and Suspension
