### ISSUE TITLE
Enable `Collections` and update edit and view pages to allign with latest HM Ingest UI

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1603]
`Collections` can be registered by anyone with write access. Look at https://ingest.hubmapconsortium.org/new/collection for editing a collection and https://portal.hubmapconsortium.org/browse/collection/3ae4ddfc175d768af5526a010bfe95aa for viewing a collection. Most of this work has already been done but there might be some updates that we are missing.

**Comment by maxsibilla** [comment]
See https://github.com/sennetconsortium/entity-api/issues/436 as well

**Comment by libpitt** [comment]
and https://github.com/sennetconsortium/entity-api/issues/437
