### ISSUE TITLE
Provenance Graph "Sticky"/Unmoving

### ISSUE THREAD

**Issue by bhonick** [sennetconsortium/portal-ui#1616]
Hi @maxsibilla, I have been running into some issues with the provenance graph on entity pages. One of the two following scenarios occurs:

- On page load, I cannot move the chain around at all, which obscures some entities like samples and derived datasets.
- If I try to go into the expanded view, I can move the provenance chain a little, but then it becomes stuck.

**Comment by maxsibilla** [comment]
@bhonick Can you provide a screenshare/video of this behavior?

**Comment by maxsibilla** [comment]
@bhonick Also what browser are you using?
