### ISSUE TITLE
Modify dataset type facet hierarchy to utilize `assay_displayname`

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1622]
I believe currently this is using `dataset_type_hierarchy` and `dataset_type`. The top level field will remain `dataset_type_hierarchy` but we should instead use `assay_displayname` for the second level.

**Comment by tjmadonna** [comment]
This should be as easy as changing this line to `assay_displayname.keyword`. Also changing line 57 to `assay_displayname`
https://github.com/sennetconsortium/portal-ui/blob/a488950c8598a1d1d789194c179af27cc392a342/src/config/search/entities.js#L60
