### ISSUE TITLE
Add New Facet to Upload View on Data Portal

### ISSUE THREAD

**Issue by bhonick** [sennetconsortium/portal-ui#1644]
@maxsibilla Would it be possible to add a new facet to the data sharing portal that allows for the sorting out of uploads that have all of their primary datasets in the `published` state?

![image](https://github.com/user-attachments/assets/857fa0b8-f653-4a87-9f99-9ad82959c421)

**Comment by maxsibilla** [comment]
@bhonick All or just some?

**Comment by bhonick** [comment]
@maxsibilla all uploads

**Comment by bhonick** [comment]
@maxsibilla Or, maybe, the facet could appear if only `Reorganized` uploads are selected?

**Comment by maxsibilla** [comment]
@bhonick Sorry I meant if all datasets in the upload are published or at least 1 is published

**Comment by bhonick** [comment]
@maxsibilla In that case, yes, whether all datasets are published. This kind of face twill be useful for me to filter out which uploads don't require more curation.
