### ISSUE TITLE
Wireframe/mockup of public search and dataset display pages

### ISSUE THREAD

**Issue by shirey** [sennetconsortium/portal-ui#173]
- In the wireframe show the conditionalFacets and think of ways to expand this functionality
- We want to show Provenance for all the entities but utilizing a network graphing approach (see Neo4) rather than the column/box visual in HuBMAP
  - Need to find a proper tool to support this (d3 or vis network graph maybe)
  - This visualization could potentially be large so this section should have an expand feature to utilize the full page

**Comment by libpitt** [comment]
Dropping this here: https://neo4j.com/developer/neo4j-browser/

**Comment by maxsibilla** [comment]
@libpitt The issue is that we are getting the data from elasticsearch in the portal
