### ISSUE TITLE
RUI registration is hardcoded to male in the samples.jsx

### ISSUE THREAD

**Issue by bherr2** [sennetconsortium/portal-ui#1753]
We've been trying to track down why data uploaders have been seeing registrations be incorrect. After a lot of digging, I see that the RUI is being forced to load the male reference organs using a hardcoded string here: <https://github.com/sennetconsortium/portal-ui/blob/main/src/pages/edit/sample.jsx#L398>. This needs to be set dynamically to `male` or `female` based on the sample's source.

**Comment by maxsibilla** [comment]
@bherr2 If metadata has not been added to the Source at the time of RUI registration should we default to a specific sex or can we prompt the user the specify this in the UI?

**Comment by bherr2** [comment]
Not sure how easy it is on your side, but having them select the sex from outside the RUI would be best. Otherwise, I believe you can set that to undefined there and here: <https://github.com/sennetconsortium/portal-ui/blob/5c51db99b12e8f5be6bd2f9b229e1fa6083fa0fc/src/components/custom/edit/sample/rui/RUIIntegration.js#L101> will result in a registration popup in the RUI. Its best if that doesn't happen so you have more control, but it could work in a pinch.

**Comment by maxsibilla** [comment]
@bherr2 I am setting `sex` to `undefined` when no sex is specified in the metadata of the Source but it results in no organ appearing:
<img width="1498" alt="image" src="https://github.com/user-attachments/assets/e2fa6d70-3ccf-48ad-b276-6d146482d58f">

I also need to manually expand `Registration Metadata` to select the sex
<img width="1491" alt="image" src="https://github.com/user-attachments/assets/bb07c290-f01e-4304-8a6d-804e59be2742">

**Comment by bherr2** [comment]
Ok, I wasn't sure if undefined sex was going to work.

**Comment by maxsibilla** [comment]
@bherr2 Any recommendations for how we should handle this use case then? We grab the sex prior to the user launching the RUI registration component so we could detect an `undefined` value and show a message directing the user to set the sex manually

**Comment by bherr2** [comment]
Yeah, I think that'd be best. It might be best from a user standpoint if the Register button when its undefined have two buttons, something like `Register (Male Source)` | `Register (Female Source)`, then no need to send a popup. But either way, having them confirm the sex they want to use before starting the RUI is important.

**Comment by bherr2** [comment]
Yeah! I think that'd be the simplest solution. When you know the sex, then there is just one button `Register location`.

**Comment by maxsibilla** [comment]
@bherr2 Yep that is how it will now operate. I can do some more testing then will let you know when its on produciton

**Comment by bherr2** [comment]
Great! Thanks for your quick work. This should help a lot.
