### ISSUE TITLE
Table on Uploads not displaying `Organ` properly

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#1781]
https://data.dev.sennetconsortium.org/upload?uuid=393a2e8116c7d013af0bd42ae25c856e/

<img width="1415" alt="Image" src="https://github.com/user-attachments/assets/f276aef9-5d7a-4414-bf17-ba46607cff7f" />

**Comment by maxsibilla** [comment]
Looks like the /datasets endpoint (https://entity-api.dev.sennetconsortium.org/uploads/393a2e8116c7d013af0bd42ae25c856e/datasets) is not returning `origin_samples` and therefore this field can't be displayed

**Comment by libpitt** [comment]
This should be fine with https://github.com/sennetconsortium/entity-api/pull/557

![Image](https://github.com/user-attachments/assets/55afbb3f-cb2e-4f55-8025-972b84ef6175)
