### ISSUE TITLE
Move application logic regarding dropdown menus (assay types, organ types, etc.) to Ontology API

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#198]

**Comment by libpitt** [comment]
https://guesdt.com/SimpleKnowledgeVisualization.html?sheet=1L5HkcsIw5k5-A5YqnCGfknZctf3S7oeU1Vu9_hYE3is
https://docs.google.com/spreadsheets/d/1L5HkcsIw5k5-A5YqnCGfknZctf3S7oeU1Vu9_hYE3is/edit#gid=1198062010

[#8](https://github.com/sennetconsortium/devops/issues/8)

**Comment by libpitt** [comment]
For the Sample category dropdown, it's: https://ontology.api.hubmapconsortium.org/valueset?parent_sab=SENNET&parent_code=C000463&child_sabs=SENNET

But subject to change.
Spreed sheet for list of codes:
https://docs.google.com/spreadsheets/d/1L5HkcsIw5k5-A5YqnCGfknZctf3S7oeU1Vu9_hYE3is/edit#gid=1226135889

**Comment by libpitt** [comment]
Sample category https://ontology.api.hubmapconsortium.org/valueset?parent_sab=SENNET&parent_code=C020076&child_sabs=SENNET

**Comment by libpitt** [comment]
Assay Types: https://ontology.api.hubmapconsortium.org/valueset?parent_sab=SENNET&parent_code=C000001&child_sabs=SENNET
