### ISSUE TITLE
RUI shows on organ samples but should show on block samples

### ISSUE THREAD

**Issue by SamSedivy** [sennetconsortium/portal-ui#204]
The RUI should show only on block samples. Need to find the parent organ of the block sample to know which organ the RUI should open with.

The button is hidden and needs some padding at the bottom. Use padding-bottom: 60px on the #unityContainer.

**Comment by maxsibilla** [comment]
If any ancestor is a Sample with Sample Category of "organ" and an organ type supported by the RUI tool AND the current sample has a sample category of "block" then the RUI tool will be accessible
