### ISSUE TITLE
Remove "Provenance" sections from all view screens and replace with a list of ancestors only.

### ISSUE THREAD

**Issue by shirey** [sennetconsortium/portal-ui#21]
For the "view" pages add the information block for the ancestor (Source in HuBMAP) entity for Samples and the table view of ancestors for datasets.

**Comment by maxsibilla** [comment]
We currently have something similar that displays ancestor information with "SourceInformationBox.jsx" which is used by "pages/edit/sample.jsx" so this might help complete this task
