### ISSUE TITLE
Investigate the order of entity_type facets jumping around when a specimen_type is selected. This may be a search-ui quirk and not something we can change.

### ISSUE THREAD

**Issue by DerekFurstPitt** [sennetconsortium/portal-ui#23]
When selecting a specimen type via the checkbox, the order of the entity type checkboxes jumps around. Not major but a visual inconsistency in the ui. See if this is something we can fix on our end. If its a quirk of the elastic search search-ui itself, it may not be something we can change.

**Comment by libpitt** [comment]
Just looked into this a bit. @elastic/search-ui just keeps selected items to the top of the respective facets category list.

**Comment by DerekFurstPitt** [comment]
@libpitt Gotcha. I would still consider this an undesirable behavior. It certainly looks buggy when watching the facets jump around in order. I wonder if this behavior can be overridden in elastic/search-ui

**Comment by libpitt** [comment]
Yes. It does look odd. Not the usual behavior like we see on Amazon's version of facets on their website and other places. I was working on another issue and suggested a workflow for handling these oddities in the future.

**Comment by maxsibilla** [comment]
With the modified facet layout this is no longer an issue
