### ISSUE TITLE
Organ Type dropdown menu not being hidden when Sample Category gets updated

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#242]
To reproduce:

1. Create new sample
2. Select `SNT297.JNWS.459` as ancestor
3. Select "Organ" from Sample Category
4. Change the ancestor to `SNT966.KZZL.693`

**Comment by libpitt** [comment]
There is a change that needs your confirmation so I can update the test where needed. Steps to reproduce:
1. Go to Create Entity > Sample
2. Select a Sample of Organ type as ancestor
3. Please verify the listed options of the Sample Category. Before there were multiple other options, 6 (+ 1=7 the ----) to be exact, now it just has Suspension listed.

This was the cypress test for details: 
![Portal-UI Entity Constraints -- While creating an entity of type Sample, the following constraints apply -- When a Sample of type Organ is selected as ancestor -- A tissue block, section, suspension, bodily fluid, organ or organ piece can be a descen](https://user-images.githubusercontent.com/115558393/209002219-b573ee64-5cbc-4854-84a6-7be9386cb845.png)


cc @maxsibilla @SamSedivy
