### ISSUE TITLE
Inital support for validation and ingest of metadata

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#258]
While we do not yet have the specifications for what metadata we will be ingesting we can at least begin to port over the HuBMAP code that exists for metadata ingestion.

**Comment by maxsibilla** [comment]
While we do not yet have the specifications for what metadata we will be ingesting we can at least begin to port over the HuBMAP code that exists for metadata ingestion.

**Comment by libpitt** [comment]
1. Port over relevant documentation from HubMAP's [ingest validation tools](https://github.com/hubmapconsortium/ingest-validation-tools) to [docs.senn](https://docs.sennetconsortium.org/).
2. Fork [ingest validation tools](https://github.com/hubmapconsortium/ingest-validation-tools) as a submodule within SenNet's ingest-api.
    a. Create working endpoint for consumption

**Comment by libpitt** [comment]
✅ Docs ported https://docs.sennetconsortium.org/libraries/ingest-validation-tools/
✅ Working endpoint for consumption created
![success-upload](https://user-images.githubusercontent.com/115558393/213565350-656b9688-8ab1-40c6-8357-03469287a3c1.png)

![fail-upload](https://user-images.githubusercontent.com/115558393/213565347-98a2edc9-670b-45ac-977f-4d909191ee04.png)

The functionality is now currently set within `ingest-api` & `portal-ui` for further wire framing design changes and logical updates. Currently, if a user uploads bad metadata the status span updates with a cross icon and a `Unacceptable Metadata` link  to download the error report .json file.

Good metadata uploads has a metadata property within the response to be sent with the form submission.

cc @maxsibilla @shirey
