### ISSUE TITLE
Entity constraints bug when creating sample

### ISSUE THREAD

**Issue by SamSedivy** [sennetconsortium/portal-ui#389]
Create a sample with this ancestor SNT587.MDQF.664 and observe the sample categories dropdown.

Organ should not appear.

Investigate POST 404 https://entity-api.dev.sennetconsortium.org/constraints?relationship_direction=descendants

**Comment by maxsibilla** [comment]
When the ancestor is an Organ (SNT587.MDQF.664) BUT the organ isn't blood (BD) the entity constraint request fails with a 404 and all sample category options are available

When the ancestor is a Suspension (SNT896.RRHS.953) the response from Entity API is:
`[{"entity_type":"dataset"}]`
and all sample category options are available.

**Comment by maxsibilla** [comment]
Need to modify entity constraints to set that a Suspension can only be a descendant of a Suspension
