### ISSUE TITLE
Add server-side next.js logging for better debugging in addition to the browser logging. For example, when the next.js calls entity-api/search-api, we can log more details of the request/response internally without exposing to the browser.

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#42]

**Comment by SamSedivy** [comment]
Notes for sam
1. Investigate why each line of JSON is printed as a separate log message. Make the logs look better. 
2. Create a separate log group for PROD. 
3. Pass the log group as an environment variable in the docker-compose.yml so we can specify the DEV/PROD log group
