### ISSUE TITLE
Add note during creation/editing of Human Sources of where to send metadata information to

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#428]
- This will only be shown if the entity has no saved metadata
- If there is saved metadata then we should either indicate that it exists, show it to them, or present a button to view the JSON of the entity to confirm what the metadata currently is

**Comment by libpitt** [comment]
@maxsibilla  Do we have text/copy for what the note should say in terms of "please send to..." instructions for the user?
