### ISSUE TITLE
Modify table results to use datatables

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#530]
Use datatables for the results/search page will accomplish a few things:

- Tables will be more consistent across the portal
- The "Sort By" button can be removed as that functionality will be supported by datatables
- Instead of issuing a POST to the Search API to handle pagination, a single request to retrieve the entirety of the elasticsearch cluster will be made and pagination will be handled by datatables. This request already filters the fields returned by elasticsearch so entire documents are not returned to the search page

**Comment by libpitt** [comment]
Considerations:
1. Table modals
2. Prevention of selecting same ancestor in Dataset registration
3. GTM
