### ISSUE TITLE
Investigate how cypress tests are able to set the data type to "bulk RNA" when the ancestor is a block

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#602]
https://data.dev.sennetconsortium.org/edit/dataset?uuid=bff9c8c741bda27c391c4e992e81a27a/

Due to the entity constraints set by the Entity API the only allowable data type is Lightsheet Microscopy

**Comment by libpitt** [comment]
@maxsibilla  Just looked over the Dataset registration. It is fine. Looking at the registration date though, this might have been around the time after ubkg integration when we had issues with casing and mismatch. I remember it was once just `Lightsheet`. Now it is `Lightsheet Microscopy`. If you look at that example Dataset, there is no data_types value in the response, so naturally by default it is selecting the first item in the list, which is Bulk `RNA-seq`
