### ISSUE TITLE
Add download TSV functionality to search page

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#604]
1) Add always present checkboxes to the results table
2) Add "Download" button that will convert the selected entities into a single TSV file containing basic information (will need to define this)

**Comment by bhonick** [comment]
Basic info that would be most helpful would be the following:
SenNet ID
UUID
Source Type
Organ Type
Assay Type

**Comment by maxsibilla** [comment]
In addition we should add any row headers that are visible in the search result table such as "Lab ID", "Group", "Status", etc.
