### ISSUE TITLE
Generalize Data Ingest Board for use with SenNet

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#771]
We will need to reach out to Derek to assist with this. We want to reuse the code rather than fork and modify. Will need to add additional endpoints in either Ingest or Entity API.

**Comment by libpitt** [comment]
https://github.com/hubmapconsortium/data-ingest-board

**Comment by maxsibilla** [comment]
@libpitt The ingest board has a button to switch between "datasets" and "uploads" but uploads are not supported by SenNet so that button will not be needed for us. 

Also if its not too difficult, try to see if you can set up the css for the navbar to use the same color grey (#505250) that's used on the portal based on the configuration.

**Comment by maxsibilla** [comment]
- [ ] Utilize React’s Context API
- [ ] Correct use of Component functionality
- [ ] Split independent Components into their own respective files
- [ ] Utilize CSS pre-processors like Sass

**Comment by libpitt** [comment]
Generalization task list:
- [ ] Prepare JSON to be read in as site copy / locale
- [ ] Rename variables with `hubmap` as substrings therein
- [ ] DRY longer if/else statement

**Comment by libpitt** [comment]
### Required fixes:

- [ ] React key prop complaints
- [ ] Ada invalid color contrasts used with Dataset.status

**Comment by libpitt** [comment]
### Code optimization recommendations:

- [ ] DRY migrated code in AppContext
- [ ] DRY components/Login/index.js
