### ISSUE TITLE
Investigate elastic search metadata parameters being strings rather than numbers

### ISSUE THREAD

**Issue by tjmadonna** [sennetconsortium/portal-ui#799]
Following parameters are strings in elastic search rather than numbers
`metadata.weight_value`
`metadata.volume_value`
`metadata.pathology_distance_value`
`metadata.section_thickness_value`
`metadata.suspension_entity_number`

**Comment by tjmadonna** [comment]
Elastic search returns
> Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [metadata.weight_value] in order to load field data by uninverting the inverted index. Note that this can use significant memory.

Changing to the keyword field returns
> Field [metadata.weight_value.keyword] of type [keyword] is not supported for aggregation [histogram]

Changing these fields to numbers will be more straight forward. [Another issue](https://github.com/sennetconsortium/search-api/issues/76) created.

**Comment by maxsibilla** [comment]
Related to issue [#76](https://github.com/sennetconsortium/search-api/issues/76)
