### ISSUE TITLE
Create definitions for dataset statuses and apply a tooltip anywhere status is visible

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#805]

**Comment by libpitt** [comment]
https://docs.google.com/document/d/133qgBOSfpeTDqL111brYtFBIQMcBEPyf0HCmeixZkhw/edit

**Comment by libpitt** [comment]
> New - The data provider has begun to upload data but is not ready for validation or processing via the ingest pipeline.
> Submitted - The data provider has finsihed uploading data and the data is ready for validation.
> Invalid - The data did not pass validation prior to processing via the ingest pipeline.
> Error - An error occurred during processing via the ingest pipeline.
> Processing - The data is currently being processed via the ingest pipeline.
> QA - The data has been successfully processed via the ingest pipeline and is awaiting data provider curation.
> Published - The data has been successfully curated and released for public use.
