### ISSUE TITLE
Investigate error created by conditional facets fix

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#822]
The following is produced locally when deselecting a facet that another facets is conditionally dependent upon:
```
Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
```

It appears to be related to the following block of code:
https://github.com/dbmi-pitt/search-ui/blob/317fb74b046312a17ff7407fa32c4e7f50c8e94b/components/core/Facets.jsx#L39-L47

**Comment by tjmadonna** [comment]
This was address in search-ui PR [#58](https://github.com/dbmi-pitt/search-ui/pull/58)
