### ISSUE TITLE
User is able to copy token based url from history, even after a logout, and regain authentication

### ISSUE THREAD

**Issue by libpitt** [sennetconsortium/portal-ui#823]
A user is able to copy browser history url with token info and regain authentication to the portal.

On HM, no such token based url is in history so problem does not present itself there.

Ideally after logout, the token should become void. So even after copying a previous token based url, a user cannot just regain authentication.

Would be nice to avoid displaying the details in the url like HM does.

**Comment by maxsibilla** [comment]
Looks like this can be reproduced with the Ingest UI (https://ingest.hubmapconsortium.org/)
