### ISSUE TITLE
Add source type to TSV/JSON infodump

### ISSUE THREAD

**Issue by bhonick** [sennetconsortium/portal-ui#830]
The current infodump (generating TSV/JSONs from the checkboxes) specifies the organ for a dataset, but not the source. The source should be part of the infodump.

**Comment by maxsibilla** [comment]
@bhonick The current way the TSV download works is that it pulls the fields shown in the results table. So if a user filters by "Entity Type" then downloads a TSV this should work. 

I did however notice an issue with TSV not returning data for selected export (works for all)

**Comment by bhonick** [comment]
@maxsibilla Thanks, that clarifies.
