### ISSUE TITLE
Align footer items horizontally on mobile view

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#837]
<img width="450" alt="image" src="https://github.com/sennetconsortium/portal-ui/assets/7218802/ef1f565b-a6cb-4a95-81a4-bc46bb8ac51f">

**Comment by libpitt** [comment]
@maxsibilla  Can you supply more details on how this should look?

**Comment by maxsibilla** [comment]
@libpitt I think the sections "About", "Policies" and "Funding" should all be horizontally aligned just like the SenNet logo and the copyright notice

**Comment by libpitt** [comment]
@maxsibilla  There isn't enough space to align all three columns, it's definitely going to look congested on small screens.

**Comment by maxsibilla** [comment]
@libpitt This is what is looks like if you just set all the unordered lists to have `text-align: center`. The css would need to be modified to only happen on mobile. 
<img width="449" alt="image" src="https://github.com/sennetconsortium/portal-ui/assets/7218802/5bf11cb2-ebd7-47a9-b724-872f29e96098">

**Comment by libpitt** [comment]
@maxsibilla  Thanks! I thought you meant horizontally align the containers.

**Comment by maxsibilla** [comment]
Sorry for the confusion
