### ISSUE TITLE
Export Selected Yields Blank TSV

### ISSUE THREAD

**Issue by bhonick** [sennetconsortium/portal-ui#845]
Hi @maxsibilla , a data provider reported to me that the "Export Selected to TSV" feature on the portal is currently broken. It only yields a blank TSV file. A recording of this phenomena is attached.
![Peek 2023-08-29 13-31](https://github.com/sennetconsortium/portal-ui/assets/71984404/fa76a3ff-7c0a-4386-9589-41eaab66daf1)

**Comment by maxsibilla** [comment]
@bhonick We noted this problem on this issue #830. We have a PR to main that will resolve this later in the week

**Comment by bhonick** [comment]
@maxsibilla Thanks! I'll go ahead and close this.
