### ISSUE TITLE
Bulk Registration Needs Confirmation Modal

### ISSUE THREAD

**Issue by bhonick** [sennetconsortium/portal-ui#846]
Hi @maxsibilla , a data provider noticed that there is not a confirmation message/modal/pop-up that appears at the completion of the bulk registration process, with the webpage merely hanging. The provider requested that we add some kind of modal that says "Your entities have been successfully registered" or a similar message. Additionally, they asked if we could include a mechanism to download a TSV/JSON of the newly registered entities' IDs in that same hypothetical modal.

**Comment by libpitt** [comment]
@bhonick We do have this functionality. 

<img width="1271" alt="Screen Shot 2023-08-29 at 4 02 28 PM" src="https://github.com/sennetconsortium/portal-ui/assets/115558393/afe5ab02-5738-4ddb-8bd0-82de68fbd321">

Which entity was the user trying to bulk register? 

cc @maxsibilla

**Comment by bhonick** [comment]
@libpitt Thanks for pointing that out -- I confirmed that on my end on TEST for the sample type, organ. Could this be a PROD-specific issue, or is more likely that it's something locally on the date provider's end?

![image](https://github.com/sennetconsortium/portal-ui/assets/71984404/edfa3ad0-7d43-482a-b9cf-d500e2eb3a64)

cc @maxsibilla
