### ISSUE TITLE
Add UI support for bulk data uploads

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#852]
We want to still support bulk registration of datasets but need to add support for data uploads

- [x] `Data` should appear above Datasets in the dropdown

<img width="336" alt="image" src="https://github.com/sennetconsortium/portal-ui/assets/7218802/585d50be-7dc3-4cf0-905a-dfff00c7e123">

- [x]  The modal to create this should be larger but still have the following fields

<img width="617" alt="image" src="https://github.com/sennetconsortium/portal-ui/assets/7218802/6f31b573-e3f3-4fa1-a150-152eba073e94">

We currently only show the groups select menu if they are a member of more than one group so we can maintain that functionality for consistency sake. 
The link to the data submission guide can point to here: https://docs.google.com/document/d/1UeUCZmjRTr7qIXnVLDKj6ix_XI9yxNFRn5w3R5Pzkf4

- [x] We need to meet and wireframe how a landing page for the uploads should look but we should be able to re-use a lot of existing components. We will probably need to implement a `Dataset` table though  (https://ingest.hubmapconsortium.org/upload/81ab1f8ff2cb528f249b7fa6d81c58a2)

**Comment by maxsibilla** [comment]
Components needed for `Upload` view page:

- We want to show the entity type, the SenNet ID, and the `status` (there won't be other badges like for datasets) 

<img width="400" alt="image" src="https://github.com/sennetconsortium/portal-ui/assets/7218802/f0bb42e1-f63b-43e9-aaea-b4c0bab1a228">

- We want a `Summary` section that will display the `title` and `description` as well as an relevant dates (`last_modified_timestamp`, `created_timestamp`)

<img width="1488" alt="image" src="https://github.com/sennetconsortium/portal-ui/assets/7218802/8b08e2fd-2634-4c16-8ba2-ace7dc6ae2b4">

- We want the `Files` section 
- We need to create a new section titled `Datasets` that will be a datatable with the following attributes:
<img width="1273" alt="image" src="https://github.com/sennetconsortium/portal-ui/assets/7218802/38c165b1-49a8-44a8-a8d2-ef6762ff3677">

- We want the `Attribution` section

**Comment by libpitt** [comment]
@maxsibilla  "Data should appear above Datasets in the dropdown" 

I think you meant below Datasets, is that right. It's below on HM and Upload contain details to multiple Datasets, so by semantics think it should be below. 

Please confirm.

**Comment by maxsibilla** [comment]
@libpitt I think because we want to highlight uploads over dataset registration for bulk we want it above.  Also on the Ingest UI there is no option for bulk dataset.

**Comment by libpitt** [comment]
@maxsibilla Okay I see. Guess it doesn't matter then, could be on either side, because when we enter an upload it is in fact a single upload, not a bulk of uploads, though it can produce a bulk of registered datasets.

**Comment by maxsibilla** [comment]
Logic for Upload edit page

- If the user is a data admin AND the status is either `Invalid` or `Error` we want to show the property `validation_message` (this is similar to how we handle pipeline_message for datasets)
<img width="1501" alt="image" src="https://github.com/sennetconsortium/portal-ui/assets/7218802/1f57827e-d622-4c54-a106-eb629b3e3230">

- If the user is a data admin AND the status is either `Invalid`, `Error`, or `Submitted` show the `Revert` button
- If the user is a data admin AND the status is either `Valid` or `Submitted` show the `Reorganize` button
- If the status is NOT `Processing` or `Reorganized` we show the button `Validate` which calls the Ingest API's /validate endpoint
- If the status is `New` or `Valid` then show the `Submit` button

- The buttons for `submit`, `revert`, `validate`, and `reorganize` should all have a modal so the user needs to confirm the action twice
