### ISSUE TITLE
Investigate utilizing shared cookie between portal and data ingest board to eliminate the need to re-login on the board

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#859]
Currently, after login `info` is stored in a cookie with the domain set as ".sennetconsortium.org". We will need to test if this is enough to maintain a user's logged in status when traveling between the portal and the data ingest board. On HuBMAP the Ingest UI stores `info` in localstorage which probably explains why the user needs to log in again on the ingest board.

**Comment by libpitt** [comment]
@maxsibilla This already works as we have it. User can log into data.dev then go to path / of prod site and they'll get auto logged in. To ensure this works on other paths, looks like we just need to copy this code that's in `pages/index.js` to the `useEffect` hook in `AppContext`, assumingely.

```
            let info = getCookie('info')
            if (info) {
                info = atob(info)
                setCookie(
                    'groups_token',
                    JSON.parse(info).groups_token
                )
            } 
        }
```
