### ISSUE TITLE
Connect the contents of the dropdown menus in the edit/create pages to an ontology

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#87]

**Comment by libpitt** [comment]
It looks like what we'd need to do is to determine the SenNet related codes needed to be supplied to the ontology api. For example, code SENNET C000005 corresponds to the list of organs.

**Comment by libpitt** [comment]
https://docs.google.com/spreadsheets/d/1V1ECU4L6lY9KReMJFOO-2WzVwBPQm673wATkmDBxSgg/edit#gid=1811201763
