### ISSUE TITLE
Create `Organ` specific view pages

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#907]
We want to create 2 primary view pages: 
1) A landing page of all organs supported by SenNet (see https://portal.hubmapconsortium.org/organ)
2) A specific landing page for each organ (see https://portal.hubmapconsortium.org/organ/kidney)

We will need to discuss which pieces we can easily replicate and will update this card to address components that will need to be developed.

After this work is done we will also need to add links to the badges on landing pages 
<img width="305" alt="image" src="https://github.com/sennetconsortium/portal-ui/assets/7218802/fe20933f-5718-4301-b64f-a74b2017d48b">

**Comment by tjmadonna** [comment]
We'll need icons for Adipose Tissue and Muscle

**Comment by maxsibilla** [comment]
@tjmadonna We might have to double up on icons. We can probably use the same icon of `skin` for `adipose tissue` and `muscle` for the time being. BTW here are all of the icons https://cdn.jsdelivr.net/gh/cns-iu/md-icons@main/other-icons/organs/

**Comment by tjmadonna** [comment]
Sounds good. Right now I just have them in as placeholders.

![Screenshot 2023-12-06 at 9 46 49 AM](https://github.com/sennetconsortium/portal-ui/assets/8182608/077f58d7-51f1-4320-ac03-60186324188c)
