### ISSUE TITLE
Fix how the CCF RUI tool loads in the portal

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#917]
Currently the RUI tool loads at the top of the page and a user can simply scroll down and out of view of it. We should load the tool inside a modal or iframe and ensure that when a user tries to close out of it we prompt them with a confirmation alert

**Comment by tjmadonna** [comment]
Implemented loading the RUI tool in a modal.

From Max
> add a confirmation when a user closes the modal either by pressing ESC or “Close”. We want to warn them that they will lose their work if they dont click “Review and Register”
