### ISSUE TITLE
Allow public access (not logged in) to the UI and search of only published and public data

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#98]

**Comment by libpitt** [comment]
Thanks @maxsibilla  As a starter question, is there somewhere I can look to determine those fields related to access level and publication status?

Looking through the network tab I can see some of the fields for the search payload request...

Looked at the config.js and can see the search query configuration that is required for the SearchProvider ...
https://docs.elastic.co/search-ui/api/core/configuration#autocomplete-query

**Comment by libpitt** [comment]
@maxsibilla  I am thinking the best way to move forward with this is through usage of the context api to avoid prop drilling etc. I am thinking this is a probably a good time to integrate this feature as well for the future if we ever need to have language changes (I see hard coding of copy/content strings). But just incase there are caveats which I may not be aware of just yet, do you have any concerns about using the context api ... ?

**Comment by libpitt** [comment]
> - Apply the appcontext logic to the pages located under `/pages/edit`
> 
> - Replace the logout button with a login button if the user is not logged in. This will mainly be on the search and view pages (source, sample, dataset)
> 
> - Intelligently redirect users to `/search` when they visit the base url (this may require us to restructure some files inside the pages directory). That way if a user visits the portal they see the search results rather than a login screen first. Maybe we just create a `login` page and move the logic from `index` there
